default_platform(:android)

ENV["FASTLANE_HTTP_TIMEOUT"] = "600"

platform :android do
  desc "Lane For Android Firebase App Distibution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:566469475610:android:1f68a719378f26998fc0a3",
      firebase_cli_token: "1//03nJjs-Cim37hCgYIARAAGAMSNwF-L9IrxjU6qm-SyHt0ndp4eAMxiKzaToe54prL363mCm81V7ojNXGaQQ8olxNfD9bDyan-_3w",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "marwaelmasry592002@gmail.com",
      release_notes: "First Fastlane FireBase Distribution DOCDOC",
      upload_timeout: 600
    )
  end
end



